# Generated by Django 2.1.7 on 2019-04-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionform', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippet',
            new_name='QuestionOne',
        ),
    ]
