# Generated by Django 2.1.7 on 2019-04-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionform', '0003_questiontwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
            ],
        ),
    ]
